version: '3'

include:
 - proxy.yaml

services:
    
  web:
    build:
      context: .
      dockerfile: Dockerfile.python
    networks:
      backend:
        ipv4_address: 172.20.0.5
    volumes:
    - wp_data:/var/www/html
    restart: on-failure #no, on-failure , always(default), unless-stopped.
    ports:
      - 5000:5000
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
    env_file:
      - .env
    depends_on:
      - db

  db:
#    image: mysql:8
    image: mariadb:10.6.4-focal
    command: "--default-authentication-plugin=mysql_native_password"
    networks:
      backend:
        ipv4_address: 172.20.0.10
    restart: on-failure
    ports:
      - 3306:3306
    environment:
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_ROOT_HOST=%
    env_file:
       - .env


networks:
  backend:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24

volumes:
  wp_data: {}
